### ISSUE TITLE
Nicht strukturierte Daten im Profil

### ISSUE THREAD

**Issue by johanneskoester** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#32]
Ein paar der Components sind nicht strukturiert abgelegt. Beispiel Codons (hier einmal als YAML):
```
- code:
    coding:
    - code: 47999-8
      display: DNA region name [Identifier]
      system: http://loinc.org
  valueString: "Codon #13 - #17"
```

Ich denke es waere das Interval maschinenlesbar und mit integers anzugeben.
